services:
  - type: web
    name: gothic-shop
    runtime: node # use the Node.js native runtime
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      # The admin token used by the admin interface. Set this secret in the Render dashboard.
      - key: ADMIN_TOKEN
        sync: false
      # SMTP configuration for newsletter notifications. Populate these in the dashboard.
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
